/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.api.gateway;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class LibraryTest {
    @Test public void testRepeatedWord() {
        Library classUnderTest = new Library();
        assertEquals("book", classUnderTest.repeatedWord("a book is the book that is a"));
    }
}
