/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.api.gateway;


import java.util.Hashtable;

public class Library {

    public String repeatedWord(String string) {
        String[] arrString = string.split(" ");
        Hashtable<String,Integer> hashtable = new Hashtable<>();

        for (String s: arrString) {

            String lowercased = s.toLowerCase();
            if(hashtable.containsKey(lowercased)) return lowercased;

            hashtable.put(lowercased,1);
        }

        return "";

    }
}
